
export const ANSWER_QUESTION_REQUEST = 'ANSWER_QUESTION_REQUEST'
export const ANSWER_QUESTION_RESPONSE_FAILURE = 'ANSWER_QUESTION_RESPONSE_FAILURE'
export const ANSWER_QUESTION_RESPONSE_SUCCESS = 'ANSWER_QUESTION_RESPONSE_SUCCESS'
