
export const NEW_QUESTION_REQUEST = 'NEW_QUESTION_REQUEST'
export const NEW_QUESTION_RESPONSE_FAILURE = 'NEW_QUESTION_RESPONSE_FAILURE'
export const NEW_QUESTION_RESPONSE_SUCCESS = 'NEW_QUESTION_RESPONSE_SUCCESS'
