
export const GET_QUIZZES_REQUEST = 'GET_QUIZZES_REQUEST'
export const GET_QUIZZES_RESPONSE_FAILURE = 'GET_QUIZZES_RESPONSE_FAILURE'
export const GET_QUIZZES_RESPONSE_SUCCESS = 'GET_QUIZZES_RESPONSE_SUCCESS'
