export const CREATE_ACCOUNT_REQUEST = 'CREATE_ACCOUNT_REQUEST'
export const CREATE_ACCOUNT_RESPONSE_FAILURE = 'CREATE_ACCOUNT_RESPONSE_FAILURE'
export const CREATE_ACCOUNT_RESPONSE_SUCCESS = 'CREATE_ACCOUNT_RESPONSE_SUCCESS'

export const GET_ACTIVE_SESSION_REQUEST = 'GET_ACTIVE_SESSION_REQUEST'
export const GET_ACTIVE_SESSION_RESPONSE_FAILURE = 'GET_ACTIVE_SESSION_RESPONSE_FAILURE'
export const GET_ACTIVE_SESSION_RESPONSE_SUCCESS = 'GET_ACTIVE_SESSION_RESPONSE_SUCCESS'

export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_RESPONSE_FAILURE = 'LOGIN_RESPONSE_FAILURE'
export const LOGIN_RESPONSE_SUCCESS = 'LOGIN_RESPONSE_SUCCESS'

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST'
export const LOGOUT_RESPONSE_FAILURE = 'LOGOUT_RESPONSE_FAILURE'
export const LOGOUT_RESPONSE_SUCCESS = 'LOGOUT_RESPONSE_SUCCESS'
