export const CREATE_ACCOUNT_REQUEST = 'CREATE_ACCOUNT_REQUEST'
export const CREATE_ACCOUNT_RESPONSE_FAILURE = 'CREATE_ACCOUNT_RESPONSE_FAILURE'
export const CREATE_ACCOUNT_RESPONSE_SUCCESS = 'CREATE_ACCOUNT_RESPONSE_SUCCESS'

export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_RESPONSE_FAILURE = 'LOGIN_RESPONSE_FAILURE'
export const LOGIN_RESPONSE_SUCCESS = 'LOGIN_RESPONSE_SUCCESS'
