// export const GET_ACTIVE_SESSION_REQUEST = 'GET_ACTIVE_SESSION_REQUEST'
// export const GET_ACTIVE_SESSION_RESPONSE_FAILURE = 'GET_ACTIVE_SESSION_RESPONSE_FAILURE'
// export const GET_ACTIVE_SESSION_RESPONSE_SUCCESS = 'GET_ACTIVE_SESSION_RESPONSE_SUCCESS'

export const GET_SESSION_INFO_REQUEST = 'GET_SESSION_INFO_REQUEST'
export const GET_SESSION_INFO_RESPONSE_FAILURE = 'GET_SESSION_INFO_RESPONSE_FAILURE'
export const GET_SESSION_INFO_RESPONSE_SUCCESS = 'GET_SESSION_INFO_RESPONSE_SUCCESS'

